#!/usr/bin/env php
<?php

define('ROOT', __DIR__);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new SON\Commands\ClassGenerator);

$application->run();
